#ifndef DHCP_H
#define DHCP_H

#include <stdint.h>
#include <time.h>

#define DHCP_SERVER_PORT  67
#define DHCP_CLIENT_PORT  68
#define DHCP_OPTIONS_LEN  312
#define DHCP_HEADER_SIZE  236
#define DHCP_MAGIC_COOKIE_SIZE 4
#define ETH_MTU           1500

// op field
#define BOOTREQUEST 1   // package from client to server
#define BOOTREPLY   2   // package from server to client

// DHCP message types (option 53)
#define DHCP_DISCOVER 1
#define DHCP_OFFER    2
#define DHCP_REQUEST  3
#define DHCP_DECLINE  4
#define DHCP_ACK      5
#define DHCP_NAK      6
#define DHCP_RELEASE  7

// DHCP option codes
#define OPT_SUBNET_MASK    1
#define OPT_ROUTER         3
#define OPT_DNS            6
#define OPT_REQUESTED_IP   50
#define OPT_LEASE_TIME     51
#define OPT_MSG_TYPE       53
#define OPT_SERVER_ID      54
#define OPT_END            255

// Magic cookie
#define DHCP_MAGIC_COOKIE 0x63825363

// Server configuration
#define SERVER_IP      "192.168.1.1"
#define SUBNET_MASK    "255.255.255.0"
#define ROUTER_IP      "192.168.1.1"    //brama?
#define DNS_IP         "8.8.8.8"
#define LEASE_TIME     3600          // seconds (1 hour)
#define IP_POOL_START  "192.168.1.100"
#define IP_POOL_END    "192.168.1.200"
#define MAX_LEASES     101           // pool size (200 - 100 + 1)

// dhcp packet
struct dhcp_packet {
    uint8_t  op;          // 1 = BOOTREQUEST, 2 = BOOTREPLY
    uint8_t  htype;       // Hardware type: 1 = Ethernet
    uint8_t  hlen;        // Hardware address length: 6 bytes (MAC)
    uint8_t  hops;        // Hops (used by relay agents)
    uint32_t xid;         // Transaction ID (random, generated by client, used as id)
    uint16_t secs;        // Seconds counted from process start
    uint16_t flags;       // Flags (0x8000 = broadcast)
    uint32_t ciaddr;      // Client IP address (discover 0.0.0.0)
    uint32_t yiaddr;      // 'Your' IP address (offered by server)
    uint32_t siaddr;      // Server IP address
    uint32_t giaddr;      // Gateway IP address (relay agent)
    uint8_t  chaddr[16];  // Client hardware address (MAC + padding)
    uint8_t  sname[64];   // Server host name
    uint8_t  file[128];   // Boot file name
    uint32_t magic_cookie; // Must be 0x63825363
    uint8_t  options[DHCP_OPTIONS_LEN]; // DHCP options (variable length)
} __attribute__((packed));

// lease entry
struct lease_entry {
    uint8_t  chaddr[16];   // Client MAC address
    uint32_t ip_addr;      // Assigned IP (network byte order)
    time_t   lease_expiry; // Unix timestamp when lease expires (0 = free)
};

// dhcp_options.c
int get_dhcp_option(struct dhcp_packet *packet, int opt_code, uint8_t *out, int out_len);
int get_dhcp_msg_type(struct dhcp_packet *packet);
int add_option(uint8_t *options, int offset, uint8_t code, uint8_t len, void *data);

// ip_pool.c
void init_lease_table();
uint32_t allocate_ip(uint8_t *chaddr);
void confirm_lease(uint8_t *chaddr, uint32_t ip);
void release_lease(uint8_t *chaddr);
uint32_t find_existing_lease(uint8_t *chaddr);

// dhcp_handler.c
void send_dhcp_reply(int sockfd, struct dhcp_packet *reply);
struct dhcp_packet build_dhcp_offer(struct dhcp_packet *discover);
struct dhcp_packet build_dhcp_ack(struct dhcp_packet *request);

#endif
